services:
  db:
    image: postgres:15.2
    env_file:
      - ./pg.env
    volumes:
      - ./psql-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  vite-react-app:
    container_name: wm-vite-react-app
    ports:
      - '5173:5173'
    build:
      context: ./vite-react-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./vite-react-app:/app
      - /app/node_modules
  asp-api:
    container_name: wm-asp-api
    build:
      context: ./asp-api
      dockerfile: Dockerfile.dev
    environment:
      - CONNECTIONSTRINGS__DEFAULT=User ID=postgres;Password=postgres;Host=db;Port=5432;Database=mono-db;
    volumes:
      - ./asp-api:/app
    ports:
      - '5000:5000'
      - '5001:5001'